openapi: 3.0.1
info:
  title: Product Service API EN
  description: This is the REST API for Product Service
  license:
    name: Apache 2.0
  version: v0.0.1
externalDocs:
  description: You can refer to the Product Service Wiki Documentation
  url: 'https://product-service-dummy-url.com/docs'
servers:
  - url: 'http://localhost:8090/productapp'
    description: Generated server url
paths:
  '/products/{id}':
    get:
      tags:
        - product-controller
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'
    put:
      tags:
        - product-controller
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      tags:
        - product-controller
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
  /products:
    get:
      tags:
        - product-controller
      operationId: getAll
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags:
        - product-controller
      operationId: addProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'
  /info:
    get:
      tags:
        - hello-controller
      operationId: sayInfo
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/InfoDto'
  /hello:
    get:
      tags:
        - hello-controller
      operationId: sayHello
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Product:
      required:
        - name
        - price
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          pattern: '[A-Za-z]+( [A-Za-z]+)*'
          type: string
        price:
          type: number
    InfoDto:
      type: object
      properties:
        message:
          type: string
        contactDetails:
          type: object
          additionalProperties:
            type: string
        onCallSupport:
          type: array
          items:
            type: string
