spring:
  kafka:
    template:
      default-topic: productapp-topic
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: productapp-events-listener-group
  application:
    name: productapp-producer
server:
  port: 8082
